export const HIGH_INTENT_KEYWORDS = [
  // === PRIMARY SERVICE + LOCATION (1-30) ===
  "marble countertops boca raton",
  "countertop fabrication boca raton",
  "countertop installation boca raton",
  "granite countertops boca raton",
  "quartz countertops boca raton",
  "quartzite countertops boca raton",
  "kitchen countertops boca raton",
  "bathroom countertops boca raton",
  "countertop replacement boca raton",
  "marble fabrication boca raton",
  "stone countertops boca raton",
  "natural stone countertops boca raton",
  "custom countertops boca raton",
  "countertop company boca raton",
  "countertop contractor boca raton",
  "marble installer boca raton",
  "countertop fabricator boca raton",
  "luxury countertops boca raton",
  "countertop store boca raton",
  "countertop showroom boca raton",
  "marble supplier boca raton",
  "granite fabrication boca raton",
  "quartz fabrication boca raton",
  "porcelain countertops boca raton",
  "sintered stone countertops boca raton",
  "dekton countertops boca raton",
  "neolith countertops boca raton",
  "silestone countertops boca raton",
  "caesarstone countertops boca raton",
  "cambria countertops boca raton",

  // === NEAR ME / HIGH COMMERCIAL INTENT (31-55) ===
  "countertop installation near me",
  "marble countertops near me",
  "granite countertops near me",
  "quartz countertops near me",
  "countertop fabricator near me",
  "kitchen countertops near me",
  "countertop replacement near me",
  "stone fabrication near me",
  "best countertop company near me",
  "affordable countertops near me",
  "countertop estimate near me",
  "free countertop estimate boca raton",
  "countertop quote boca raton",
  "best countertop fabricator boca raton",
  "top rated countertop installer boca raton",
  "5 star countertop company boca raton",
  "countertop professionals boca raton",
  "licensed countertop installer boca raton",
  "insured countertop contractor boca raton",
  "same day countertop estimate boca raton",
  "fast countertop installation boca raton",
  "affordable marble countertops boca raton",
  "cheap granite countertops boca raton",
  "discount countertops boca raton",
  "countertop deals boca raton",

  // === ROOM-SPECIFIC (56-80) ===
  "kitchen island countertop boca raton",
  "bathroom vanity countertop boca raton",
  "outdoor kitchen countertops boca raton",
  "wet bar countertop boca raton",
  "laundry room countertop boca raton",
  "fireplace surround marble boca raton",
  "marble shower walls boca raton",
  "marble floor installation boca raton",
  "marble backsplash boca raton",
  "waterfall countertop boca raton",
  "waterfall edge countertop boca raton",
  "mitered edge countertop boca raton",
  "book matched marble boca raton",
  "full slab backsplash boca raton",
  "marble accent wall boca raton",
  "marble bathroom renovation boca raton",
  "marble kitchen renovation boca raton",
  "stone bathroom vanity boca raton",
  "double vanity countertop boca raton",
  "master bath marble boca raton",
  "pool deck marble boca raton",
  "outdoor countertop fabrication boca raton",
  "summer kitchen countertops boca raton",
  "butler pantry countertop boca raton",
  "marble stairs boca raton",

  // === MATERIAL-SPECIFIC HIGH INTENT (81-115) ===
  "calacatta marble countertops boca raton",
  "carrara marble countertops boca raton",
  "statuario marble countertops boca raton",
  "calacatta gold marble boca raton",
  "taj mahal quartzite boca raton",
  "super white quartzite boca raton",
  "white marble countertops boca raton",
  "black granite countertops boca raton",
  "white quartz countertops boca raton",
  "gray quartz countertops boca raton",
  "white granite countertops boca raton",
  "blue bahia granite boca raton",
  "patagonia granite boca raton",
  "mont blanc quartzite boca raton",
  "fantasy brown granite boca raton",
  "bianco romano granite boca raton",
  "absolute black granite boca raton",
  "arctic white quartz boca raton",
  "calacatta quartz boca raton",
  "marble look quartz boca raton",
  "white macaubas quartzite boca raton",
  "cristallo quartzite boca raton",
  "dolce vita quartzite boca raton",
  "perla venata quartzite boca raton",
  "sea pearl quartzite boca raton",
  "exotic granite boca raton",
  "exotic marble boca raton",
  "imported marble boca raton",
  "italian marble boca raton",
  "brazilian granite boca raton",
  "onyx countertops boca raton",
  "travertine countertops boca raton",
  "soapstone countertops boca raton",
  "limestone countertops boca raton",
  "engineered stone countertops boca raton",

  // === COMMERCIAL / PROJECT-TYPE (116-140) ===
  "commercial countertops boca raton",
  "commercial marble installation boca raton",
  "hotel marble installation boca raton",
  "restaurant countertops boca raton",
  "office countertops boca raton",
  "condo countertop installation boca raton",
  "new construction countertops boca raton",
  "countertop renovation boca raton",
  "kitchen remodel countertops boca raton",
  "bathroom remodel countertops boca raton",
  "builder countertop supplier boca raton",
  "general contractor countertop partner boca raton",
  "multi-family countertop installation boca raton",
  "luxury home countertops boca raton",
  "custom home countertops boca raton",
  "high rise countertop installation boca raton",
  "penthouse marble installation boca raton",
  "yacht marble fabrication boca raton",
  "country club marble boca raton",
  "spa marble installation boca raton",
  "lobby marble installation boca raton",
  "reception desk stone boca raton",
  "medical office countertops boca raton",
  "dental office countertops boca raton",
  "salon countertops boca raton",

  // === SERVICE-SPECIFIC ACTIONS (141-165) ===
  "countertop templating boca raton",
  "countertop measuring boca raton",
  "countertop sealing boca raton",
  "marble polishing boca raton",
  "marble restoration boca raton",
  "marble repair boca raton",
  "granite repair boca raton",
  "countertop chip repair boca raton",
  "countertop crack repair boca raton",
  "stone sealing boca raton",
  "countertop removal boca raton",
  "old countertop removal boca raton",
  "countertop demo and install boca raton",
  "sink cutout countertop boca raton",
  "undermount sink installation boca raton",
  "cooktop cutout countertop boca raton",
  "edge profile countertop boca raton",
  "bullnose edge countertop boca raton",
  "ogee edge countertop boca raton",
  "beveled edge countertop boca raton",
  "eased edge countertop boca raton",
  "custom edge profile boca raton",
  "CNC stone fabrication boca raton",
  "laser templating countertops boca raton",
  "digital templating countertops boca raton",

  // === SOUTH FLORIDA AREA EXPANSION (166-200) ===
  "marble countertops delray beach",
  "countertop installation delray beach",
  "granite countertops delray beach",
  "quartz countertops delray beach",
  "marble countertops deerfield beach",
  "countertop installation deerfield beach",
  "marble countertops pompano beach",
  "countertop installation pompano beach",
  "marble countertops coral springs",
  "countertop installation coral springs",
  "marble countertops parkland",
  "countertop installation parkland",
  "marble countertops coconut creek",
  "countertop installation coconut creek",
  "marble countertops boynton beach",
  "countertop installation boynton beach",
  "marble countertops highland beach",
  "countertop installation highland beach",
  "marble countertops west palm beach",
  "countertop installation west palm beach",
  "marble countertops fort lauderdale",
  "countertop installation fort lauderdale",
  "marble countertops lighthouse point",
  "countertop installation lighthouse point",
  "marble countertops lake worth",
  "countertop installation lake worth",
  "marble countertops wellington",
  "countertop installation wellington",
  "countertop fabrication south florida",
  "marble countertops south florida",
  "best countertop company south florida",
  "luxury marble fabrication south florida",
  "countertop installation palm beach county",
  "marble countertops palm beach county",
  "countertop fabrication broward county",
] as const;

export const KEYWORD_CLUSTERS = {
  primary: HIGH_INTENT_KEYWORDS.slice(0, 30),
  nearMe: HIGH_INTENT_KEYWORDS.slice(30, 55),
  roomSpecific: HIGH_INTENT_KEYWORDS.slice(55, 80),
  materialSpecific: HIGH_INTENT_KEYWORDS.slice(80, 115),
  commercial: HIGH_INTENT_KEYWORDS.slice(115, 140),
  serviceActions: HIGH_INTENT_KEYWORDS.slice(140, 165),
  areaExpansion: HIGH_INTENT_KEYWORDS.slice(165, 200),
} as const;
